# Generated by Django 2.1.2 on 2018-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('lat', models.TextField()),
                ('long', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
