# Generated by Django 2.1.2 on 2018-12-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20181203_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldborder',
            options={'ordering': ('name',)},
        ),
    ]
