# Generated by Django 2.1.2 on 2018-12-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20181207_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublinbikes',
            name='available_bike_stands',
            field=models.IntegerField(default=0, verbose_name='available_bike_stands'),
        ),
        migrations.AlterField(
            model_name='dublinbikes',
            name='available_bikes',
            field=models.IntegerField(default=0, verbose_name='available_bikes'),
        ),
        migrations.AlterField(
            model_name='dublinbikes',
            name='stand_name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dublinbikes',
            name='total_bike_stands',
            field=models.IntegerField(default=0, verbose_name='bike_stands'),
        ),
    ]
