# Generated by Django 2.1.2 on 2018-12-07 03:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20181207_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinbikes',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=6432, verbose_name='position'),
        ),
    ]
