# Generated by Django 2.1.2 on 2018-12-07 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20181207_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinbikes',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 3, 55, 10, 235930, tzinfo=utc)),
        ),
    ]
