# Generated by Django 2.1.2 on 2018-12-08 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20181208_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starbucks',
            old_name='street',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dublinbikes',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 1, 26, 35, 710594, tzinfo=utc)),
        ),
    ]
