version: '3'

services:
        web:
                command: python3 manage.py runserver --insecure 0.0.0.0:80
                volumes:
                        - .:/code
                ports:
                        - "80:80"
